### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by vinayakumarr** [olsgaard/Datamining-project#1]
what this code does? is it text classification or what?.

**Comment by olsgaard** [comment]
It's a final project for a first year university class called datamining.

It is a text classifier. It predicts the author of a text from a known list of possible authors (note that it cannot decide that a text is not from the list of known authors)

Here's the final paper: https://drive.google.com/file/d/0B_YJcy36AScWazVJOGo0RlNJYVE/view?usp=sharing

If you are interested in authorship attribution, this repo is a much better place to start/look: https://github.com/robertlayton/authorship_tutorials

**Comment by vinayakumarr** [comment]
Thank you for your response. I will try with my data set. I need your help
regarding this and my data set is other language

**Comment by walkingintopeople** [comment]
The data loading and data structures are a mess in terms of replacing data.

I would recommend you follow the tutorial I linked to and try that instead.
It should have similar performance.
